name: image_compression_flutter_example
description: Demonstrates how to use the image_compression_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  filesystem_picker: ^2.0.0-nullsafety.0
  image_compression_flutter:
    path: ../
  image_picker: ^0.8.2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
