name: image_compression_flutter
description: A Flutter extension to compress and resize the images (JPG, PNG, WEBP).
version: 1.0.0
homepage: https://github.com/eyro-labs/image_compression_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_image_compress: ^1.0.0
  image_compression: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
